
export const locationSchema = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttarakhand',
    'Uttar Pradesh',
    'West Bengal',
    'Andaman and Nicobar',
    'Chandigarh',
    'Delhi NCR',
    'Puducherry',
    'Ladakh',
    'Jammu and Kashmir',
    'Nagaland',
    'Tamil Nadu',
    'Amaravati',
    'Itanagar',
    'Dispur',
    'Patna',
    'Raipur',
    'Panaji',
    'Gandhinagar',
    'Chandigarh',
    'Shimla',
    'Ranchi',
    'Bengaluru',
    'Thiruvananthapuram',
    'Bhopal',
    'Mumbai',
    'Imphal',
    'Shillong',
    'Aizawl',
    'Kohima',
    'Bhubaneswar',
    'Chandigarh',
    'Jaipur',
    'Gangtok',
    'Chennai',
    'Hyderabad',
    'Agartala',
    'Dehradun',
    'Lucknow',
    'Kolkata',
    'Port Blair',
    'Chandigarh',
    'Daman',
    'Kavaratti',
    'New Delhi',
    'Puducherry',
    'Leh',
    'Srinagar',
    'Nagaland'
];

export const professionSchema = [
    'Accountant',
    'Actor',
    'Actuary',
    'Agricultural Worker',
    'Architect',
    'Artist',
    'Astrologer',
    'Attorney',
    'Ayurvedic Practitioner',
    'Banker',
    'Barber',
    'Bartender',
    'Biologist',
    'Carpenter',
    'Cashier',
    'Chef',
    'Chemist',
    'Civil Servant',
    'Coach',
    'Data Analyst',
    'Dentist',
    'Designer',
    'Doctor',
    'Domestic Help',
    'Economist',
    'Electrician',
    'Engineer',
    'Event Planner',
    'Farmer',
    'Fisherman',
    'Firefighter',
    'Fitness Trainer',
    'Government Employee',
    'IAS Officer',
    'IT Consultant',
    'Journalist',
    'Jewelry Designer',
    'Lawyer',
    'Librarian',
    'Mechanic',
    'Mobile App Developer',
    'NGO Worker',
    'Nurse',
    'Pharmacist',
    'Photographer',
    'Pilot',
    'Plumber',
    'Police Officer',
    'Potter',
    'Professor',
    'Psychologist',
    'Real Estate Agent',
    'Rickshaw Driver',
    'Scientist',
    'Social Media Manager',
    'Social Worker',
    'Software Developer',
    'Street Vendor',
    'Teacher',
    'Textile Worker',
    'Tour Guide',
    'Tutor',
    'Veterinarian',
    'Waiter',
    'Weaver',
    'Writer',
    'Yoga Instructor',
    'Other'
];

export const interestsSchema = [
    'Acrobatics',
    'Acting',
    'Aerial yoga',
    'Airbrushing',
    'Amateur radio',
    'Animation',
    'Antique collecting',
    'Aquascaping',
    'Archery',
    'Archaeology',
    'Architecture',
    'Art collecting',
    'Art therapy',
    'Astrology',
    'Astronomy',
    'Athletic training',
    'Audio engineering',
    'Auto detailing',
    'Backpacking',
    'Badminton',
    'Baking',
    'Balloon twisting',
    'Barbering',
    'Bartending',
    'Base jumping',
    'Basketball',
    'Baton twirling',
    'Beach volleyball',
    'Beekeeping',
    'Beer brewing',
    'Belly dancing',
    'Bicycle polo',
    'Biking',
    'Bird watching',
    'Blacksmithing',
    'Blogging',
    'BMX racing',
    'Board games',
    'Boat building',
    'Bodybuilding',
    'Bookbinding',
    'Book restoration',
    'Bowling',
    'Boxing',
    'Brewing kombucha',
    'Bridge building',
    'Bullet journaling',
    'Butchering',
    'Calligraphy',
    'Camping',
    'Candle making',
    'Candy making',
    'Canoeing',
    'Car customization',
    'Cardistry',
    'Card games',
    'Cartography',
    'Carving',
    'Ceramics',
    'Cheese making',
    'Cheesemongering',
    'Chemical experiments',
    'Chess',
    'Chocolate making',
    'Cliff diving',
    'Clock making',
    'Clothing design',
    'Coffee roasting',
    'Coin collecting',
    'Comic book collecting',
    'Composting',
    'Computer building',
    'Conlanging',
    'Conspiracy theories',
    'Constellation mapping',
    'Cookie decorating',
    'Cooking',
    'Cosplay',
    'Couponing',
    'Crayon art',
    'Creative writing',
    'Crocheting',
    'Cross-stitching',
    'CrossFit',
    'Crosswords',
    'Cryptocurrency trading',
    'Crystal healing',
    'Culinary tourism',
    'Curling',
    'Cycling',
    'Dace dance',
    'Dance choreography',
    'Darts',
    'Debating',
    'Decoupage',
    'Deep sea fishing',
    'Diorama making',
    'Dirt biking',
    'Diving',
    'DIY electronics',
    'DNA genealogy',
    'Dog training',
    'Doll making',
    'Dowsing',
    'Drone racing',
    'Drumming',
    'Dumpster diving',
    'Dungeons & Dragons',
    'Ebru painting',
    'Eco-friendly living',
    'Electroplating',
    'Embroidery',
    'Engraving',
    'Entertainment law',
    'Entrepreneurship',
    'Equestrian vaulting',
    'Escape rooms',
    'Esports',
    'Etching',
    'Ethical hacking',
    'Event planning',
    'Experimental film',
    'Extreme ironing',
    'Falconry',
    'Fashion design',
    'Feng shui',
    'Fencing',
    'Fermenting foods',
    'Film criticism',
    'Film making',
    'Financial investing',
    'Fire dancing',
    'Fire poi',
    'Fish keeping',
    'Flag football',
    'Flower arranging',
    'Fly tying',
    'Foraging',
    'Foreign languages',
    'Fossil hunting',
    'Fountain pen collecting',
    'Freeganism',
    'Freestyle football',
    'Furniture flipping',
    'Game development',
    'Gardening',
    'Genealogy',
    'Geocaching',
    'Ghost hunting',
    'Glass blowing',
    'Go (game)',
    'Golf',
    'Graffiti art',
    'Graphic novels',
    'Grilling',
    'Guitar building',
    'Gunsmithing',
    'Hacky sack',
    'Haiku writing',
    'Hand lettering',
    'Hang gliding',
    'Hardware hacking',
    'Hatha yoga',
    'Herbalism',
    'Heritage conservation',
    'Hiking',
    'Historical reenactment',
    'Hobby horsing',
    'Home automation',
    'Homebrewing',
    'Home staging',
    'Horticulture',
    'Horseback archery',
    'Horseback riding',
    'Hula hooping',
    'Hydroponics',
    'Ice carving',
    'Ice climbing',
    'Ice hockey',
    'Ice skating',
    'Ikebana',
    'Improv comedy',
    'Indoor gardening',
    'Inline skating',
    'Insect collecting',
    'Interior design',
    'Inventing',
    'Jazz dancing',
    'Jewelry making',
    'Jigsaw puzzles',
    'Jiu-jitsu',
    'Juggling',
    'Jump rope',
    'Karaoke',
    'Kayaking',
    'Kendo',
    'Kickboxing',
    'Kite fighting',
    'Kite surfing',
    'Knife making',
    'Knitting',
    'Kombucha brewing',
    'Lacrosse',
    'Lampworking',
    'Landscape painting',
    'Lapidary',
    'Lasertag',
    'Leatherworking',
    'Lego building',
    'Letterboxing',
    'Linguistics',
    'Lino printing',
    'Lion dancing',
    'Live action role-playing',
    'Lock picking',
    'Lomography',
    'Longboarding',
    'Luthiery',
    'Macrame',
    'Magic tricks',
    'Makeup artistry',
    'Manga collecting',
    'Marathon running',
    'Marble sculpting',
    'Martial arts',
    'Meme creation',
    'Metal detecting',
    'Metalworking',
    'Microbiology',
    'Microexpression analysis',
    'Miniature art',
    'Mixology',
    'Model UN',
    'Model rocketry',
    'Mosaic art',
    'Motocross',
    'Motorcycle touring',
    'Mountain biking',
    'Movie memorabilia',
    'Mushroom foraging',
    'Music composition',
    'Music production',
    'Nail art',
    'Needle felting',
    'Neuroscience',
    'Nordic walking',
    'Origami',
    'Paddleboarding',
    'Paintball',
    'Painting',
    'Paleontology',
    'Parkour',
    'Paragliding',
    'Parkour',
    'Pastry arts',
    'Pattern making',
    'Pen spinning',
    'Perfume making',
    'Pet photography',
    'Philosophy',
    'Photogrammetry',
    'Photography',
    'Pilates',
    'Pin collecting',
    'Pinochle',
    'Poi spinning',
    'Poker',
    'Pole dancing',
    'Pottery',
    'Powerlifting',
    'Practical effects',
    'Protesting',
    'Public speaking',
    'Puppetry',
    'Puzzle design',
    'Pyrography',
    'Quilling',
    'Quilting',
    'Racquetball',
    'Radio control',
    'Railfanning',
    'Rap battles',
    'Reading',
    'Record collecting',
    'Recycling art',
    'Renovating',
    'Resin art',
    'Restoration',
    'Robot combat',
    'Rock balancing',
    'Rock climbing',
    'Role-playing games',
    'Roller derby',
    'Roulette',
    'Rubiks cube',
    'Running',
    'Saddle making',
    'Sailing',
    'Salsa dancing',
    'Sand art',
    'Scrapbooking',
    'Scuba diving',
    'Sea glass collecting',
    'Self-defense',
    'Sewing',
    'Shoemaking',
    'Shuffleboard',
    'Silversmithing',
    'Skateboarding',
    'Skeet shooting',
    'Sketch comedy',
    'Skydiving',
    'Slacklining',
    'Soap making',
    'Social media',
    'Songwriting',
    'Spearfishing',
    'Speedcubing',
    'Spelunking',
    'Spinning wool',
    'Spoken word',
    'Sports betting',
    'Spreadsheet art',
    'Stamp collecting',
    'Stand-up comedy',
    'Star gazing',
    'Steampunk',
    'Stone skipping',
    'Storytelling',
    'Street art',
    'Street food',
    'Street magic',
    'Sudoku',
    'Survivalism',
    'Swimming',
    'Sword fighting',
    'Table tennis',
    'Taekwondo',
    'Tapestry weaving',
    'Tarot reading',
    'Tattoo art',
    'Taxidermy',
    'Tea blending',
    'Technical drawing',
    'Terrarium building',
    'Thrifting',
    'Tie-dye',
    'Topiary',
    'Toy collecting',
    'Travel hacking',
    'Treasure hunting',
    'Tree shaping',
    'T-shirt design',
    'Ultimate frisbee',
    'Upcycling',
    'Urban exploration',
    'Vegan cooking',
    'Vegetable carving',
    'Ventriloquism',
    'Video blogging',
    'Vintage cars',
    'Violin making',
    'Virtual reality',
    'Voice acting',
    'Volunteering',
    'Warhammer',
    'Watchmaking',
    'Watercolor',
    'Weapon collecting',
    'Weather tracking',
    'Weightlifting',
    'Whittling',
    'Wine tasting',
    'Wood burning',
    'Woodturning',
    'Worldbuilding',
    'Wrestling',
    'Writing',
    'Yo-yoing',
    'Yoga',
    'Zentangle',
    'Ziplining',
    'Zumba'
];

//toasts
import { toast } from 'react-hot-toast';
import VerifiedIcon from '@mui/icons-material/Verified';
import NewReleasesIcon from '@mui/icons-material/NewReleases';

export const showToast = (type, message) => {
    const commonConfig = {
        duration: 3000,
        position: 'top-center',
        ariaProps: { role: 'status', 'aria-live': 'polite' },
    };

    if (type === 'success') {
        toast(
            <div className="flex center g5">
                <VerifiedIcon />
                {message}
            </div>,
            {
                ...commonConfig,
                style: { color: 'rgb(0, 189, 0)' },
                className: 'success',
            }
        );
    } else if (type === 'error') {
        toast(
            <div className="flex center g5">
                <NewReleasesIcon />
                {message}
            </div>,
            {
                ...commonConfig,
                style: { color: 'red' },
                className: 'failed',
            }
        );
    }
};

